# Generated by Django 3.0.2 on 2020-01-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200103_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='active',
            new_name='isActive',
        ),
    ]
