# Generated by Django 3.0.2 on 2020-01-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200103_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='isActive',
            new_name='active',
        ),
    ]
